[workspace]
members = [
    # Libs
    "lib",
    # Services
    "services/acl-service",
    # Add other services here
]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
