version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
      # - "443:443" # Uncomment this line if you want to use https
    depends_on:
      - acl-service
      - shared-service
    volumes:
      # - ./certs:/etc/nginx/certs # Uncomment this line if you want to use https
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-tier