version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  acl-db:
    image: surrealdb/surrealdb:1.0.0
    ports:
      - 8000:8000
    container_name: acl-db
    networks:
      - app-tier
    user: root
    command: start --log debug --user root --pass root file:/db-data/mydatabase.db
    volumes:
      - acl-servicedb:/db-data
  acl-service:
    image: elonaire/acl-service:latest
    ports:
      - 3001:3001
    container_name: acl-service
    networks:
      - app-tier
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: acl-service
    environment:
      - GOOGLE_OAUTH_CLIENT_ID=${GOOGLE_OAUTH_CLIENT_ID}
      - GOOGLE_OAUTH_CLIENT_SECRET=${GOOGLE_OAUTH_CLIENT_SECRET}
      - GOOGLE_OAUTH_AUTHORIZE_URL=${GOOGLE_OAUTH_AUTHORIZE_URL}
      - GOOGLE_OAUTH_ACCESS_TOKEN_URL=${GOOGLE_OAUTH_ACCESS_TOKEN_URL}
      - GOOGLE_OAUTH_REVOKE_TOKEN_URL=${GOOGLE_OAUTH_REVOKE_TOKEN_URL}
      - GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
      - GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}
      - GITHUB_OAUTH_AUTHORIZE_URL=${GITHUB_OAUTH_AUTHORIZE_URL}
      - GITHUB_OAUTH_ACCESS_TOKEN_URL=${GITHUB_OAUTH_ACCESS_TOKEN_URL}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
      - DATABASE_NAMESPACE=${DATABASE_NAMESPACE}
      - DATABASE_NAME_ACL=${DATABASE_NAME_ACL}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT_ACL=${DATABASE_PORT_ACL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - acl-db


# Add any network or volume configurations if needed
volumes:
  acl-servicedb: