name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'dev']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SHOULD_RUN: 'true'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_deploy_acl:
    runs-on: ubuntu-latest
    # needs: [build]
    outputs:
      should_run: ${{ steps.set_should_run.outputs.should_run }}

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
      - uses: actions/checkout@v3

      - id: set_should_run
        name: Check for ACL Service Changes
        run: |
          SHOULD_RUN="false"
          for file in ${{ github.event.pull_request.changed_files }}
          do
            if [[ "$file" == services/acl-service/* ]]; then
              SHOULD_RUN="true"
              break
            fi
          done
          echo "SHOULD_RUN=$SHOULD_RUN" >> $GITHUB_ENV
          echo "::set-output name=should_run::$SHOULD_RUN"

      - if: env.SHOULD_RUN == 'true'
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - if: env.SHOULD_RUN == 'true'
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - if: env.SHOULD_RUN == 'true'
        name: Build the Docker image
        run: docker-compose  -f docker-compose.yml -f docker-compose.acl.yml build
    
      - if: env.SHOULD_RUN == 'true'
        name: Push the Docker image
        run: docker-compose push

  build_and_deploy_shared_service:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.changed_files, 'services/shared-service/')
    # needs: [build]

    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker-compose  -f docker-compose.yml -f docker-compose.shared.yml build
    
      - name: Push the Docker image
        run: docker-compose push

  automerge:
    runs-on: ubuntu-latest

    needs: [build_and_deploy_acl, build_and_deploy_shared_service]
    if: needs.build_and_deploy_acl.result == 'success' || needs.build_and_deploy_shared_service.result == 'success'

    steps:
      - id: automerge
        name: automerge
        uses: 'pascalgn/automerge-action@v0.15.5'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          MERGE_LABELS: ''
